package com.github.amateurishprogrammer.electronicsknowledge.ui
import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import coil3.compose.AsyncImage
import com.github.amateurishprogrammer.electronicsknowledge.data.*
@Composable fun KnowledgeApp(vm:KnowledgeViewModel=viewModel()){val s by vm.state.collectAsState();KnowledgeTheme(s.dark?:false){Scaffold(bottomBar={if(s.selected==null)NavigationBar{listOf(Destination.HOME to Icons.Default.Home,Destination.CATEGORIES to Icons.Default.List,Destination.FAVORITES to Icons.Default.Favorite,Destination.RECENT to Icons.Default.History).forEach{(d,i)->NavigationBarItem(s.destination==d,{vm.navigate(d)},{Icon(i,null)},label={Text(when(d){Destination.HOME->"首页";Destination.CATEGORIES->"分类";Destination.FAVORITES->"收藏";Destination.RECENT->"最近"})})}}}){p->AnimatedContent(s.selected,Modifier.padding(p),label="entry"){e->if(e==null)Catalog(s,vm)else Detail(e,s.states[e.id]?.favorite==true,vm::back,{vm.favorite(e.id)})}}}}
@Composable private fun Catalog(s:AppUiState,vm:KnowledgeViewModel){Column(Modifier.fillMaxSize().padding(horizontal=20.dp)){Row(Modifier.fillMaxWidth().padding(top=22.dp,bottom=16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("电子专业知识库",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("元器件手册 · "+s.entries.size+" 条",color=MaterialTheme.colorScheme.primary)};IconButton({vm.dark(!(s.dark?:false))}){Icon(if(s.dark==true)Icons.Default.LightMode else Icons.Default.DarkMode,"切换主题")}};if(s.destination==Destination.HOME)OutlinedTextField(s.query,vm::search,Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text("搜索名称、型号、别名或关键词")},singleLine=true);if(s.error!=null)Text(s.error,color=MaterialTheme.colorScheme.error);if(s.loading){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()};return};if(s.destination==Destination.CATEGORIES&&s.selectedCategory==null){LazyColumn{items(s.categories,key={it.id}){c->Row(Modifier.fillMaxWidth().clickable{vm.selectCategory(c.id)}.padding(vertical=18.dp),verticalAlignment=Alignment.CenterVertically){Text(c.title,Modifier.weight(1f),style=MaterialTheme.typography.titleLarge);Text(s.entries.count{it.categoryId==c.id}.toString());Icon(Icons.Default.ChevronRight,null)}}};return};val list=vm.visible(s);if(s.destination==Destination.CATEGORIES&&s.selectedCategory!=null)TextButton({vm.navigate(Destination.CATEGORIES)}){Icon(Icons.Default.ArrowBack,null);Text("返回分类")};if(list.isEmpty())Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text(if(s.destination==Destination.FAVORITES)"还没有收藏条目" else "没有找到匹配内容")}else LazyColumn(contentPadding=PaddingValues(vertical=14.dp)){items(list,key={it.id}){e->Column(Modifier.fillMaxWidth().clickable{vm.open(e)}.padding(vertical=13.dp)){Row{Text(e.title,Modifier.weight(1f),style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold);if(s.states[e.id]?.favorite==true)Icon(Icons.Default.Favorite,null,tint=MaterialTheme.colorScheme.primary)};Text(e.englishName,color=MaterialTheme.colorScheme.primary,style=MaterialTheme.typography.labelMedium);Text(e.summary,modifier=Modifier.padding(top=4.dp))};HorizontalDivider()}}}}
@Composable private fun Detail(e:KnowledgeEntry,f:Boolean,back:()->Unit,toggle:()->Unit){val uri=LocalUriHandler.current;LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp)){item{Row{IconButton(back){Icon(Icons.Default.ArrowBack,"返回")};Spacer(Modifier.weight(1f));IconButton(toggle){Icon(if(f)Icons.Default.Favorite else Icons.Default.FavoriteBorder,"收藏",tint=MaterialTheme.colorScheme.primary)}};Text(e.title,style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Bold);Text(e.englishName,color=MaterialTheme.colorScheme.primary);AsyncImage("file:///android_asset/content/"+e.images.first().assetPath,e.images.first().altText,Modifier.fillMaxWidth().height(180.dp),contentScale=ContentScale.Fit);Text(e.summary,style=MaterialTheme.typography.titleMedium,modifier=Modifier.padding(vertical=18.dp))};items(e.sections){x->Text(x.title,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.primary,modifier=Modifier.padding(top=18.dp,bottom=8.dp));Text(x.body)};item{Text("资料来源",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=24.dp,bottom=8.dp));e.sources.forEach{x->Text(x.publisher+" · "+x.title);Text(x.url,color=MaterialTheme.colorScheme.primary,modifier=Modifier.clickable{uri.openUri(x.url)}.padding(bottom=12.dp))};Text("图片："+e.images.first().attribution+" · "+e.images.first().license,style=MaterialTheme.typography.labelSmall)}}}
