package com.github.amateurishprogrammer.electronicsknowledge.ui
import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.github.amateurishprogrammer.electronicsknowledge.data.*
import com.github.amateurishprogrammer.electronicsknowledge.domain.*
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
enum class Destination{HOME,CATEGORIES,FAVORITES,RECENT}
data class AppUiState(val loading:Boolean=true,val error:String?=null,val categories:List<CategoryEntity> = emptyList(),val entries:List<KnowledgeEntry> = emptyList(),val states:Map<String,EntryStateEntity> = emptyMap(),val query:String="",val destination:Destination=Destination.HOME,val selectedCategory:String?=null,val selected:KnowledgeEntry?=null,val dark:Boolean?=null)
private data class Catalog(val c:List<CategoryEntity>,val e:List<KnowledgeEntry>,val s:Map<String,EntryStateEntity>)
private data class Controls(val q:String,val d:Destination,val c:String?,val s:KnowledgeEntry?)
class KnowledgeViewModel(app:Application):AndroidViewModel(app){private val repo=KnowledgeRepository(app,AppDatabase.get(app));private val theme=ThemeStore(app);private val q=MutableStateFlow("");private val d=MutableStateFlow(Destination.HOME);private val c=MutableStateFlow<String?>(null);private val sel=MutableStateFlow<KnowledgeEntry?>(null);private val err=MutableStateFlow<String?>(null);private val catalog=combine(repo.categories(),repo.entries(),repo.states()){a,b,z->Catalog(a,b.map(repo::decode),z.associateBy{it.entryId})};private val controls=combine(q,d,c,sel){a,b,z,x->Controls(a,b,z,x)};val state=combine(catalog,controls,theme.dark,err){a,b,dark,error->AppUiState(false,error,a.c,a.e,a.s,b.q,b.d,b.c,b.s,dark)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),AppUiState());init{viewModelScope.launch{runCatching{repo.ensureContent()}.onFailure{err.value=it.message?:"内容导入失败"}}};fun search(v:String){q.value=v;d.value=Destination.HOME;sel.value=null};fun navigate(v:Destination){d.value=v;sel.value=null;c.value=null};fun selectCategory(id:String){c.value=id;d.value=Destination.CATEGORIES};fun open(e:KnowledgeEntry){sel.value=e;viewModelScope.launch{repo.viewed(e.id)}};fun back(){sel.value=null};fun favorite(id:String)=viewModelScope.launch{repo.toggle(id)};fun dark(v:Boolean)=viewModelScope.launch{theme.set(v)};fun visible(s:AppUiState):List<KnowledgeEntry>{val base=when(s.destination){Destination.FAVORITES->s.entries.filter{s.states[it.id]?.favorite==true};Destination.RECENT->s.entries.filter{s.states[it.id]?.lastViewedAt!=null}.sortedByDescending{s.states[it.id]?.lastViewedAt};Destination.CATEGORIES->s.selectedCategory?.let{z->s.entries.filter{it.categoryId==z}}?:emptyList();else->s.entries};if(s.query.isBlank())return base;val map=base.associateBy{it.id};return SearchRanker.rank(base.map{SearchCandidate(it.id,it.title,it.englishName,it.aliases,it.keywords,it.summary)},s.query).mapNotNull{map[it.id]}}}
